In [65]:
import numpy as np

In [15]:
!pip install numpy


[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [58]:
np_array_1 = np.array([1,2,3,4])
print(np_array_1)
print(type(np_array_1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [60]:
np_array_2 = np.array([[1,2,3],[4,5,6]])
print(np_array_2)

[[1 2 3]
 [4 5 6]]


In [23]:
one_array = np.ones((3,3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
full_array = np.full((4,4),3)
print(full_array)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [29]:
eye_array = np.eye(5)
print(eye_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
random_array = np.random.random((3,3))
print(random_array)

[[0.8719227  0.78477195 0.96002774]
 [0.9721915  0.40236137 0.54937312]
 [0.2498013  0.77191684 0.01668174]]


In [34]:
arange_array = np.arange(10)
print(arange_array)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
reshape_array = arange_array.reshape((2,5))
print(reshape_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [40]:
# 행렬 연산
x = np.array([1,2,3])
y = np.array([4,5,6])

In [64]:
# 행렬의 합
print(x + y)
print(np.add(x,y))

[0.54055829 1.73734555 1.16186379 1.20629799 1.8102464  0.93821166
 0.81099108 0.95486299 0.19210589 0.73924319 1.61538902 0.27533341
 1.13107257 0.88687773 0.64597982 0.87763299 0.69267107 1.03499424
 1.48902293 1.00401906 1.0246662  0.47300446 1.77840937 0.9675783
 0.38786083 0.35597712 1.3657647  0.97303713 0.5313615  0.25945173
 0.8011978  1.01871231 1.06181829 1.42765815 0.7367035  0.90788704
 0.85367278 1.17413928 0.84031111 0.91068581 1.11601091 0.28228218
 1.23863347 1.15648026 1.24658158 1.14203772 1.40152312 1.15229942
 0.23198365 1.60759859]
[0.54055829 1.73734555 1.16186379 1.20629799 1.8102464  0.93821166
 0.81099108 0.95486299 0.19210589 0.73924319 1.61538902 0.27533341
 1.13107257 0.88687773 0.64597982 0.87763299 0.69267107 1.03499424
 1.48902293 1.00401906 1.0246662  0.47300446 1.77840937 0.9675783
 0.38786083 0.35597712 1.3657647  0.97303713 0.5313615  0.25945173
 0.8011978  1.01871231 1.06181829 1.42765815 0.7367035  0.90788704
 0.85367278 1.17413928 0.84031111 0.9106

In [44]:
# 행렬의 차
print( x - y)
print(np.add(x,y))

[-3 -3 -3 -3]
[ 5  7  9 11]


In [46]:
# 행렬의 곱
print(x*y)
print(np.add(x,y))

[ 4 10 18 28]
[ 5  7  9 11]


In [51]:
# 행렬의 나누기
print(x / y)
print(np.divide(x,y))

[0.25       0.4        0.5        0.57142857]
[0.25       0.4        0.5        0.57142857]


In [62]:
# 행렬의 행렬곱

x2 = np.array([[1,2],[3,4]])
y2 = np.array([[5,6],[7,8]])


In [66]:
x = np.random.rand(50)
y = np.random.rand(50)

plt.scatter(x,y)
plt.show()

NameError: name 'plt' is not defined